server:
  port: 8099

spring:
  datasource:
    url: jdbc:mysql://42.194.196.68:3308/sakila?useUnicode=true
    driver-class-name: com.mysql.jdbc.Driver
    username: admin
    password: 123456

  application:
    name: redis-module-web


  redis:
    host: localhost
    port: 6379
#    password: 123456
    timeout: -1

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://42.194.196.68:7998/eureka/


mybatis:
  mapper-locations: classpath:mapper/*Dao.xml
  type-aliases-package: com.study.redis.web.submitOrderRocback.dto



